#!/bin/sh
set -eu
go build ./...
go vet ./...
test -z "$(gofmt -l .)"
go mod tidy
git diff --exit-code -- go.mod go.sum
go test -count=1 -shuffle=on -timeout 10m ./...
go test -race -count=1 -shuffle=on -timeout 10m ./internal/... ./tests/...
